version: 2.1
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/typescript-starter
    steps:
      - test:
          nodeVersion: "10"
  'node-12':
    docker:
      - image: circleci/node:12
    working_directory: ~/typescript-starter
    steps:
      - test:
          nodeVersion: "12"

commands:
  test:
    parameters:
      nodeVersion:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-node<< parameters.nodeVersion >>-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node<< parameters.nodeVersion >>-{{ checksum "package.json" }}
      - run: npm run static-checks
      - run: npm run test:ci:unit
      - run: npm run test:integration

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-12
