name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - assigned

jobs:
  dependabot-automerge:
    uses: relaycorp/shared-workflows/.github/workflows/dependabot-automerge.yml@main
