name: Process PRs

on:
  pull_request:
    types:
      - opened

jobs:
  dependabot-automerge:
    uses: relaycorp/shared-workflows/.github/workflows/prs.yml@main
    secrets:
      dependabotPAT: ${{ secrets.IRELAYBOT_PAT_PR_AUTOMATION }}
